name: bookdown
on: [push]

jobs:
  bookdown:
    name: bookdown setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install OpenSSL
        run: sudo apt-get update; sudo apt-get install libcurl4-openssl-dev; sudo apt-get install libssl-dev; date > TIME
  
      - name: Cache R Packages
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-mycache-R-heatmap-${{ hashFiles('DESCRIPTION') }}
          
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Render Book
        run: Rscript setup.R

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: commit
        run: |
          git config --global user.email jh2259@mrc-cu.cam.ac.uk
          git config --global user.name xihajun
          git add .
          git commit -m "automation bookdown" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
#  checkout-and-deploy:
#   runs-on: ubuntu-latest
#   needs: bookdown
#   steps:
#     - name: Checkout
#       uses: actions/checkout@master
#     - name: Download artifact
#       uses: actions/download-artifact@v1.0.0
#       with:
#         # Artifact name
#         name: _book # optional
#         # Destination path
#         path: _book # optional
#     - name: Deploy to GitHub Pages
#       uses: Cecilapp/GitHub-Pages-deploy@v3
#       env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#          build_dir: docs/ # "_site/" by default
#          email: ${{ secrets.EMAIL }}  # must be a verified email
